### ISSUE TITLE
Adding a minimal config example

### ISSUE THREAD

**Issue by aamir-s18** [speechmatics/ctranslate2_triton_backend#2]
Hey,

Thank you for bringing ctranslate2 to Triton! I am currently working on a project for a course using ctranslate2 and would like to host the model on Triton.

I got it up with Triton, but I am struggling to find the correct config.

Would it be possible to add a minimal example for a model?

Thank you!

**Comment by HennerM** [comment]
Hi @aamir-s18, thanks for your interest.

I am sorry that there was no documentation yet, it wasn't quite ready for public consumption. I added a very basic README in #3, let me know if this helps, you could even make some comments to brush it up.

Thanks,
Markus

**Comment by aamir-s18** [comment]
Hey @HennerM thank you for the docs! It is working :)

I will go over it tomorrow and brush it up. I made it run without the docs but it was really a wild ride to get it run.

Really thank you so much for the code and the docs! :)))

**Comment by aamir-s18** [comment]
Hey @HennerM,

I think your Readme is super clear! LGTM.

Maybe we can move this to new issues:

- Could we add support for other models than sequence to sequence? I modified the code to get it to work with [language model class](https://github.com/OpenNMT/CTranslate2/blob/master/src/models/language_model.cc). What would be a good way to generalise the current code? Unfortunately, I am not super familiar with Triton. But I would love to contribute.
- Does the current code support streaming? From my first experiments, it seems not. I didn't find any docs about how to make it work in Triton but it Triton seems to support it. Do you have some ideas or pointers?

Feel free to close this issue. Let me know if I should open a new issue.
